{
    "needUpdate":true,
    "url":"https://diandiango.coding.net/p/ddPublicFile/d/ddPublicFile/git/raw/master/raw/diandiantingshu_1.7.4.apk",
    "des":"更新内容：1.修复崩溃问题2.增加x5内核初始化逻辑",
    "constraint":false,
    "size":"11M",
    "version":174,
    "versionName":"1.7.4",
    "backWebUrl":"https://wwi.lanzoui.com/ddts"
}