{
  "needUpdate":true,
  "url":"https://cdn.githubjs.cf/Beardemon/ddpublic/blob/main/raw/ddys956_nocore.apk?raw=true",
  "des":"\n1、修复不能登录，从而导致无法收藏无法追番的问题\n2、修复播放器的一些问题如缓冲不显示图标不显示网速，如奇怪的自动播放逻辑\n3、修复投屏后无法自动暂停播放的问题",
  "constraint":false,
  "size":"10.1M",
  "version":956,
  "versionName":"9.5.6",
  "backWebUrl":"https://wwi.lanzoup.com/ddysnox5"
}
