{
    "needUpdate":true,
    "url":"https://pan.tenire.com/down.php/0ecdaa58483037e57cdc319bb0e1f60c.apk",
    "des":"\n1、优化了播放器\n2、优化部分源站无法打开的问题\n3、去除开屏页广告，加快启动速度\n4、适当调整ui，增加启动提示上次观看弹框\n5、适配安卓14，修复下载视频的问题",
    "constraint":false,
    "size":"19.2M",
    "version":960,
    "versionName":"9.6.0",
    "backWebUrl":"https://wwi.lanzoup.com/ddys"
}
