{
  "needUpdate":true,
  "url":"https://diandiango.coding.net/p/ddPublicFile/d/ddPublicFile/git/raw/master/raw/diandianyingshi_9.5.2.apk",
  "des":"\n1、修复x5播放器，使用内置播放器失败会自动用x5播放(播放器兼容性大大提升)\n2、增加追更功能，第一时间知道追的剧更了没\n3、修复解析源的重试机制\n4、首页ui微调，把没用的数据往后调\n5、修复部分源下一页数据重复问题\n6、exo播放器适配后台逻辑，可以不在频繁被杀进程",
  "constraint":true,
  "size":"9.9M",
  "version":952,
  "versionName":"9.5.2",
  "backWebUrl":"https://wwi.lanzoui.com/ddys"
}