{
    "needUpdate":true,
    "url":"https://pan.tenire.com/down.php/516da7e122b7fe64553dbcab147b04af.apk",
    "des":"\n1、修复搜索不到资源的问题\n2、全新的下载逻辑，下载更完善更强壮\n3、全新的投屏逻辑，搜索可投屏设备更快更完善\n4、修复搜索热词功能\n5、首页增加更多推荐列表\nn6、调整ui",
    "constraint":true,
    "size":"14.6M",
    "version":959,
    "versionName":"9.5.9",
    "backWebUrl":"https://wwi.lanzoup.com/ddys"
}
