{
  "needUpdate":true,
  "url":"https://diandiango.coding.net/p/ddPublicFile/d/ddPublicFile/git/raw/master/raw/diandianyingshi_9.3.8.apk?Accept-Encoding=identity",
  "des":"\n1.修复崩溃问题\n2.x5内核加载问题再次优化",
  "constraint":false,
  "size":"14M",
  "version":938,
  "versionName":"9.3.8",
  "backWebUrl":"https://wwi.lanzoui.com/ddys"
}